<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BarangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('barang')->insert([
            [
                'nama' => 'Indomie Goreng',
                'harga_beli' => 2500,
                'harga_jual' => 3000,
                'stock' => 20,
                'modal' => 50000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Chocolatos Cokelat',
                'harga_beli' => 700,
                'harga_jual' => 1000,
                'stock' => 20,
                'modal' => 14000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Wafer Nabati Cokelat',
                'harga_beli' => 600,
                'harga_jual' => 1000,
                'stock' => 20,
                'modal' => 12000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pepsodent Herbal',
                'harga_beli' => 8000,
                'harga_jual' => 10000,
                'stock' => 4,
                'modal' => 32000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pantene Sashet',
                'harga_beli' => 1500,
                'harga_jual' => 2000,
                'stock' => 10,
                'modal' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Milo Sashet',
                'harga_beli' => 2500,
                'harga_jual' => 3000,
                'stock' => 16,
                'modal' => 40000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Marimas Sashet',
                'harga_beli' => 700,
                'harga_jual' => 1000,
                'stock' => 21,
                'modal' => 14700,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Soffel',
                'harga_beli' => 1500,
                'harga_jual' => 2000,
                'stock' => 9,
                'modal' => 9000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Kopi Ya Sashet',
                'harga_beli' => 1600,
                'harga_jual' => 2000,
                'stock' => 20,
                'modal' => 32000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Wafer Superstar',
                'harga_beli' => 1750,
                'harga_jual' => 2000,
                'stock' => 10,
                'modal' => 17500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Mie Sedaap Goreng',
                'harga_beli' => 2500,
                'harga_jual' => 3000,
                'stock' => 30,
                'modal' => 75000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Aqua Botol 600ml',
                'harga_beli' => 3500,
                'harga_jual' => 5000,
                'stock' => 24,
                'modal' => 84000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Teh Pucuk Harum 350ml',
                'harga_beli' => 4000,
                'harga_jual' => 5000,
                'stock' => 15,
                'modal' => 60000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Good Day Cappuccino',
                'harga_beli' => 1000,
                'harga_jual' => 1500,
                'stock' => 25,
                'modal' => 25000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Taro Net',
                'harga_beli' => 1800,
                'harga_jual' => 2500,
                'stock' => 20,
                'modal' => 36000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Chitato Sapi Panggang',
                'harga_beli' => 7000,
                'harga_jual' => 9000,
                'stock' => 10,
                'modal' => 70000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Nextar Cokelat',
                'harga_beli' => 2500,
                'harga_jual' => 3000,
                'stock' => 18,
                'modal' => 45000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sari Roti Tawar',
                'harga_beli' => 9000,
                'harga_jual' => 11000,
                'stock' => 8,
                'modal' => 72000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Roma Malkist Abon',
                'harga_beli' => 3500,
                'harga_jual' => 4500,
                'stock' => 20,
                'modal' => 70000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Tissue Paseo Mini',
                'harga_beli' => 2500,
                'harga_jual' => 3500,
                'stock' => 15,
                'modal' => 37500,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Lasegar Rasa Jeruk',
                'harga_beli' => 4000,
                'harga_jual' => 5000,
                'stock' => 12,
                'modal' => 48000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Pop Ice Cokelat',
                'harga_beli' => 500,
                'harga_jual' => 1000,
                'stock' => 40,
                'modal' => 20000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Energen Vanila',
                'harga_beli' => 2000,
                'harga_jual' => 2500,
                'stock' => 25,
                'modal' => 50000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Super Pell Refill',
                'harga_beli' => 6000,
                'harga_jual' => 8000,
                'stock' => 10,
                'modal' => 60000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sunlight Jeruk Nipis',
                'harga_beli' => 5000,
                'harga_jual' => 7000,
                'stock' => 10,
                'modal' => 50000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Baygon Refill',
                'harga_beli' => 16000,
                'harga_jual' => 20000,
                'stock' => 5,
                'modal' => 80000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sambal ABC Botol',
                'harga_beli' => 6000,
                'harga_jual' => 8000,
                'stock' => 8,
                'modal' => 48000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Sasa Tepung Bumbu',
                'harga_beli' => 4000,
                'harga_jual' => 5000,
                'stock' => 12,
                'modal' => 48000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'Bango Kecap Manis Refill',
                'harga_beli' => 9000,
                'harga_jual' => 11000,
                'stock' => 7,
                'modal' => 63000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nama' => 'So Klin Liquid Refill',
                'harga_beli' => 7000,
                'harga_jual' => 9000,
                'stock' => 10,
                'modal' => 70000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
